### ISSUE TITLE
Cleaning up the sidebar dropdowns

### ISSUE THREAD

**Issue by jasdumas** [r-devel/cran-cookbook#26]
Perhaps we don't need drop-downs? 

```yaml

contents:
      - index.qmd
      - general_issues.qmd
      - section: "Manuals & Documentation Issues"
        contents:
          - docs_issues.qmd
      - section: "Code Issues"
        contents:
          - code_issues.qmd
      - section: "DESCRIPTION file Issues"
        contents:
          - description_issues.qmd
      - about.qmd
 ```
<img width="211" alt="Screen Shot 2024-07-15 at 2 44 16 PM" src="https://github.com/user-attachments/assets/14eb52ad-99a7-4a93-97fd-026b3693e033">
